stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/wine.csv
      - params.yaml
    outs:
      - data/processed

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
      - params.yaml
    outs:
      - model.pkl
    metrics:
      - metrics.json:
          cache: false
